/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CTR.TelefoneTipoCTR;
import Sistemas_login.utilitarios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alanbazilio
 */
public class tela_tipotelefone extends javax.swing.JDialog {

    /**
     * Creates new form tela_tipotelefone
     */
     ResultSet rsfunc;
   tela_tipotelefone objtel;
       public static int id_tel;
   
    String opcao;
     public static boolean button;
     int a = 1;
    public tela_tipotelefone(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        
        this.setBounds(0, 0, d.width = 800, d.height  = 600);
              setResizable(false);
        setFocusable(true);
         setLocationRelativeTo(null);
        pesquisartel();
        desativarBotoes();
        utilitarios u = new utilitarios();
    u.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jttipostel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tipotel = new javax.swing.JTextField();
        cradastrar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        busca = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE TIPO TELEFONE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 817, 59);

        jttipostel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jttipostel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jttipostel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jttipostelMouseClicked(evt);
            }
        });
        jttipostel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jttipostelKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jttipostel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 60, 580, 540);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Tipo de telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 60, 110, 20);
        getContentPane().add(tipotel);
        tipotel.setBounds(10, 90, 160, 30);

        cradastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        cradastrar.setText("Novo");
        cradastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cradastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cradastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cradastrar);
        cradastrar.setBounds(10, 340, 160, 40);

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(10, 380, 160, 40);

        busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atualizar.png"))); // NOI18N
        busca.setText("Atualizar dados");
        busca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });
        getContentPane().add(busca);
        busca.setBounds(10, 500, 160, 40);

        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar (1).png"))); // NOI18N
        Alterar.setText("Alterar");
        Alterar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(Alterar);
        Alterar.setBounds(10, 420, 160, 40);

        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar (1).png"))); // NOI18N
        excluir.setText(" Excluir");
        excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(10, 460, 160, 40);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cradastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cradastrarActionPerformed
        // TODO add your handling code here:
        ativarBotoes();
       pesquisartel();
       limparCampos();
        opcao = "Inserir";
        button = true;
    }//GEN-LAST:event_cradastrarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
         if(opcao.equals("Inserir")){
       Inserirtel();
       pesquisartel();
       limparCampos();
       }
        desativarBotoes();
    }//GEN-LAST:event_salvarActionPerformed

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        pesquisartel();
    }//GEN-LAST:event_buscaActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        Alterartel();
         pesquisartel();
       limparCampos();
    }//GEN-LAST:event_AlterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
          String [] options = new String[] {"Sim","Não"};

        Object ret = JOptionPane.showOptionDialog
        (null, "Tem certeza que deseja excluir: "
            + tipotel.getText() + "?","AVISO", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if(options[Integer.valueOf(ret.toString())].equals("Sim"))
        {
            Excluirtel();
             pesquisartel();
       limparCampos();
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void jttipostelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jttipostelKeyPressed
           int linha = jttipostel.getSelectedRow();
            
           
            this.tipotel.setText((String) jttipostel.getValueAt(linha, 1));
            id_tel = (int) jttipostel.getValueAt(linha, 0);
            opcao="Alterar";
            ativarBotoes();
    }//GEN-LAST:event_jttipostelKeyPressed

    private void jttipostelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jttipostelMouseClicked
        
          if(evt.getClickCount() == 2)
        {
            int linha = jttipostel.getSelectedRow();
            
       
            this.tipotel.setText((String) jttipostel.getValueAt(linha, 0));
           
            
            tela_tipotelefone.button = 
           (boolean) jttipostel.getValueAt(linha, 0);
                    
            this.dispose();
        }
    }//GEN-LAST:event_jttipostelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_tipotelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_tipotelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_tipotelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_tipotelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tela_tipotelefone dialog = new tela_tipotelefone(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public void desativarBotoes()
    {
        salvar.setEnabled(false);
        tipotel.setEnabled(false);
    }
    
    public void ativarBotoes()
    {
        salvar.setEnabled(true);
        tipotel.setEnabled(true);
    }
    
 public void Inserirtel()
    {
        TelefoneTipoCTR objfunc = new TelefoneTipoCTR();
        
        objfunc.InseretelCTR(tipotel.getText());
    }
  public void limparCampos()
    {
    tipotel.setText("");
    }
  
  public void pesquisartel()
    {
         TelefoneTipoCTR objfunc = new TelefoneTipoCTR();
        rsfunc = objfunc.PesquisartelCTR(tipotel.getText());
        
        preenche_item();
        
    }
 public void Alterartel()
    {
      
        int linha = jttipostel.getSelectedRow();
        
        TelefoneTipoCTR objcli = new TelefoneTipoCTR();
        
        objcli.AlteratelCTR(tipotel.getText(),id_tel);
    }     
  
  public void preenche_item()
    {
     String [] colunas = {"CÓDIGO","TIPO_TELFONE"};
        
        String [][] linhas ={};
        
        DefaultTableModel tablemodel = new DefaultTableModel(linhas,colunas)
        {
            public boolean CelulaEditavel(int rowIndex, int mColIndex)
            {
                return true;
            }
        };
        
        Vector <Vector> dados = new Vector();
        
        try {
            while(rsfunc.next())
            {
                Vector regVetor = new Vector();
                
                regVetor.add(rsfunc.getInt("codtipotel"));
                regVetor.add(rsfunc.getString("nometipotel"));
                dados.add(regVetor);
                tablemodel.addRow(regVetor);
            }
            jttipostel.setModel(tablemodel);
            
        } catch (SQLException ex) {
            Logger.getLogger(Bairros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }
     public void Excluirtel()
    {
      int linha = jttipostel.getSelectedRow();
        
        TelefoneTipoCTR objcli = new TelefoneTipoCTR();
        
        objcli.ExcluitelCTR(id_tel);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton busca;
    private javax.swing.JButton cradastrar;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jttipostel;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField tipotel;
    // End of variables declaration//GEN-END:variables
}
