/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CTR.FuncionarioCTR;
import Model.CidadeModel;
import Model.bairroModel;
import Model.telefoneModel;
import Model.RuaModel;
import Sistemas_login.utilitarios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class tela_funcionario extends javax.swing.JDialog {

    /**
     * Creates new form tela_funcionario
     */
    boolean cb;
    boolean cids;
    boolean ruas;
    boolean telefones;
    public static int id_funcionario;
    public static int fkcod_cidade;
    ResultSet rsfunc;
    String opcao;
    List<CidadeModel> listcidade;
    List<bairroModel> listbairro;
    List<telefoneModel> listtelefone;
    List<RuaModel> listrua;
    static boolean button;

    public tela_funcionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cb = false;
        cids = false;
        ruas = false;
        telefones = false;
        desativarBotoes();
            Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        
           this.setBounds(0, 0, d.width = 836, d.height  = 634);
        setResizable(false);
        setFocusable(true);
         setLocationRelativeTo(null);
        utilitarios u = new utilitarios();
        u.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        rua = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        bairro = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cidade = new javax.swing.JComboBox<String>();
        telefone = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        casa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionariotable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tela_princial = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        rg = new javax.swing.JFormattedTextField();
        cpf = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(852, 634));
        setMinimumSize(new java.awt.Dimension(852, 634));
        setPreferredSize(new java.awt.Dimension(852, 634));
        setResizable(false);
        setSize(new java.awt.Dimension(852, 634));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("Funcionario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 60, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("Rg:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 100, 30, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("Cpf:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 140, 40, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 180, 40, 20);

        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(funcionario);
        funcionario.setBounds(0, 80, 160, 20);

        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });
        getContentPane().add(rua);
        rua.setBounds(0, 280, 160, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setText("Cidade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 220, 70, 20);

        getContentPane().add(bairro);
        bairro.setBounds(0, 200, 160, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setText("Telefone:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 300, 60, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setText("Rua:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 260, 40, 20);

        getContentPane().add(cidade);
        cidade.setBounds(0, 240, 160, 20);

        getContentPane().add(telefone);
        telefone.setBounds(0, 320, 160, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setText("Nº.casa:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 340, 60, 20);
        getContentPane().add(casa);
        casa.setBounds(0, 360, 160, 20);

        funcionariotable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        funcionariotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        funcionariotable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        funcionariotable.setEditingColumn(1);
        funcionariotable.setEditingRow(1);
        funcionariotable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariotableMouseClicked(evt);
            }
        });
        funcionariotable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                funcionariotableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(funcionariotable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 60, 690, 540);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO FUNCIONÁRIO");

        tela_princial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reserva-64.png"))); // NOI18N
        tela_princial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tela_princial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tela_princialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(tela_princial)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tela_princial))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 59);

        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        cadastrar.setText("Novo");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(0, 390, 150, 40);

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(0, 430, 150, 40);

        deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar (1).png"))); // NOI18N
        deletar.setText("excluir");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });
        getContentPane().add(deletar);
        deletar.setBounds(0, 510, 150, 40);

        alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar (1).png"))); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(0, 470, 150, 40);

        atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atualizar.png"))); // NOI18N
        atualizar.setText("Atualizardados");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(0, 550, 150, 40);

        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(rg);
        rg.setBounds(0, 120, 160, 20);

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpf);
        cpf.setBounds(0, 160, 160, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 180, 40, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 220, 40, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 260, 40, 20);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 300, 40, 20);

        setSize(new java.awt.Dimension(868, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tela_princialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tela_princialMouseClicked
        // TODO add your handling code here:
        Tela_principal telasp = new Tela_principal(null,true);
        telasp.setVisible(true);
    }//GEN-LAST:event_tela_princialMouseClicked

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionarioActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        inserefuncionario();
        limparCampos();
        desativarBotoes();
        pesquisarfuncionaro();
    }//GEN-LAST:event_salvarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        ativarBotoes();
        limparCampos();
        opcao = "Inserir";
        button = true;
    }//GEN-LAST:event_cadastrarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        String[] options = new String[]{"Sim", "Não"};

        Object ret = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir: "
                + funcionario.getText() + "?", "AVISO", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (options[Integer.valueOf(ret.toString())].equals("Sim")) {
            excluirfuncionaro();
            limparCampos();
            desativarBotoes();
            pesquisarfuncionaro();
        }
    }//GEN-LAST:event_deletarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        alterafuncionario();
        limparCampos();
        desativarBotoes();
        pesquisarfuncionaro();
    }//GEN-LAST:event_alterarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        pesquisarfuncionaro();
    }//GEN-LAST:event_atualizarActionPerformed

    private void funcionariotableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_funcionariotableKeyPressed
        int linha = funcionariotable.getSelectedRow();

        this.funcionario.setText((String) funcionariotable.getValueAt(linha, 1));
        this.rg.setText((String) funcionariotable.getValueAt(linha, 2));
        this.cpf.setText((String) funcionariotable.getValueAt(linha, 3));
        this.casa.setText((String) funcionariotable.getValueAt(linha, 8));
        id_funcionario = (int) funcionariotable.getValueAt(linha, 0);

        opcao = "Alterar";
        ativarBotoes();
    }//GEN-LAST:event_funcionariotableKeyPressed

    private void funcionariotableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariotableMouseClicked
        if (evt.getClickCount() == 2) {
            int linha = funcionariotable.getSelectedRow();

            this.funcionario.setText((String) funcionariotable.getValueAt(linha, 1));
            this.rg.setText((String) funcionariotable.getValueAt(linha, 2));
            this.cpf.setText((String) funcionariotable.getValueAt(linha, 3));
            this.casa.setText((String) funcionariotable.getValueAt(linha, 8));

            tela_funcionario.button
                    = (boolean) funcionariotable.getValueAt(linha, 0);

            this.dispose();
        }
    }//GEN-LAST:event_funcionariotableMouseClicked

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cb = true;
        Bairros bairros = new Bairros(null,true);
        bairros.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cids = true;
        cidade cid = new cidade(null,true);
        cid.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         ruas = true;
        rua ru = new rua(null,true);
        ru.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(cb==true){
            carregabairrocmb();
            cb = false;
        }
          if(cids==true){
            carregacidadecmb();
            cids = false;
        }
            if(ruas==true){
            carregaruacmb();
            ruas = false;
        }
              if(telefones==true){
            carregatelefonecmb();
            telefones = false;
        }
 
    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           telefones = true;
        tela_telefone cid = new tela_telefone(null,true);
        cid.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tela_funcionario dialog = new tela_funcionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    public void desativarBotoes() {
        salvar.setEnabled(false);
        deletar.setEnabled(false);
        funcionario.setEnabled(false);
        rg.setEnabled(false);
        cpf.setEnabled(false);
        bairro.setEnabled(false);
        cidade.setEnabled(false);
        telefone.setEnabled(false);
        rua.setEnabled(false);
        casa.setEnabled(false);
    }

    public void ativarBotoes() {
        salvar.setEnabled(true);
        deletar.setEnabled(true);
        funcionario.setEnabled(true);
        rg.setEnabled(true);
        cpf.setEnabled(true);
        bairro.setEnabled(true);
        cidade.setEnabled(true);
        telefone.setEnabled(true);
        rua.setEnabled(true);
        casa.setEnabled(true);
    }

    public void limparCampos() {
        funcionario.setText("");
        rg.setText("");
        cpf.setText("");
        casa.setText("");
    }

    public void carregacidadecmb() {
        FuncionarioCTR objtel = new FuncionarioCTR();
        listcidade = objtel.carregaCombocidade();

        cidade.removeAllItems();
        int i = 0;

        while (i < listcidade.size()) {
            cidade.addItem(listcidade.get(i).getNomecidade());
            i++;
        }

    }

    public void carregaruacmb() {
        FuncionarioCTR objtel = new FuncionarioCTR();
        listrua = objtel.carregaComboRua();

        rua.removeAllItems();
        int i = 0;

        while (i < listrua.size()) {
            rua.addItem(listrua.get(i).getNomerua());
            i++;
        }

    }

    public void carregatelefonecmb() {
        FuncionarioCTR objtel = new FuncionarioCTR();
        listtelefone = objtel.carregaCombotelefone();

        telefone.removeAllItems();
        int i = 0;

        while (i < listrua.size()) {
            telefone.addItem(listtelefone.get(i).getNumerotel());
            i++;
        }

    }

    public void carregabairrocmb() {
        FuncionarioCTR objtel = new FuncionarioCTR();
        listbairro = objtel.carregaCombobairro();

        bairro.removeAllItems();
        int i = 0;

        while (i < listbairro.size()) {
            bairro.addItem(listbairro.get(i).getBairros());
            i++;
        }

    }

    public void inserefuncionario() {
        FuncionarioCTR objfuncionario = new FuncionarioCTR();
        objfuncionario.InserefuncionarioCTR(
                funcionario.getText(), rg.getText(), cpf.getText(),
                listbairro.get(bairro.getSelectedIndex()).getCodbairro(),
                listcidade.get(cidade.getSelectedIndex()).getCodcidade(),
                listtelefone.get(telefone.getSelectedIndex()).getCodtelefone(),
                listrua.get(rua.getSelectedIndex()).getCodrua(), casa.getText());

    }

    public void alterafuncionario() {
        FuncionarioCTR objfuncionario = new FuncionarioCTR();
        objfuncionario.AlterafuncionarioCTR(
                funcionario.getText(), rg.getText(), cpf.getText(),
                listbairro.get(bairro.getSelectedIndex()).getCodbairro(),
                listcidade.get(cidade.getSelectedIndex()).getCodcidade(),
                listtelefone.get(telefone.getSelectedIndex()).getCodtelefone(),
                listrua.get(rua.getSelectedIndex()).getCodrua(), casa.getText(), id_funcionario);

    }

    public void excluirfuncionaro() {
        int linha = funcionariotable.getSelectedRow();

        FuncionarioCTR objcli = new FuncionarioCTR();

        objcli.ExcluifuncionaroCTR(id_funcionario);
    }

    public void pesquisarfuncionaro() {
        FuncionarioCTR objfunc = new FuncionarioCTR();
        rsfunc = objfunc.PesquisarfuncionaroCTR(funcionario.getText());

        preenche_item();

    }

    public void preenche_item() {
        String[] colunas = {"CÓDIGO", "FUNCIONÁRIO", "RG", "CPF", "BAIRRO", "CIDADE", "TELEFONE", "RUA", "Nº.CASA"};

        String[][] linhas = {};

        DefaultTableModel tablemodel = new DefaultTableModel(linhas, colunas) {
            public boolean CelulaEditavel(int rowIndex, int mColIndex) {
                return true;
            }
        };

        Vector<Vector> dados = new Vector();

        try {
            while (rsfunc.next()) {
                Vector regVetor = new Vector();

                regVetor.add(rsfunc.getInt("cod_funcionario"));
                regVetor.add(rsfunc.getString("nome_funcionario"));
                regVetor.add(rsfunc.getString("rg"));
                regVetor.add(rsfunc.getString("cpf"));
                regVetor.add(rsfunc.getString("bairro"));
                regVetor.add(rsfunc.getString("nomecidade"));
                regVetor.add(rsfunc.getString("numerotel"));
                regVetor.add(rsfunc.getString("nomerua"));
                regVetor.add(rsfunc.getString("numerocasa"));
                dados.add(regVetor);
                tablemodel.addRow(regVetor);
            }
            funcionariotable.setModel(tablemodel);

        } catch (SQLException ex) {
            Logger.getLogger(tela_funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton atualizar;
    private javax.swing.JComboBox<String> bairro;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField casa;
    private javax.swing.JComboBox<String> cidade;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton deletar;
    private javax.swing.JTextField funcionario;
    private javax.swing.JTable funcionariotable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JComboBox<String> rua;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel tela_princial;
    private javax.swing.JComboBox<String> telefone;
    // End of variables declaration//GEN-END:variables
}
